export interface DeviceHardware {
  hwModel: number;
  hwModelSlug: string;
  platformioTarget: string;
  architecture: string;
  activelySupported: boolean;
}

const deviceHardwareList: DeviceHardware[] = [
  {
    hwModel: 1,
    hwModelSlug: "TLORA_V2",
    platformioTarget: "tlora-v2",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 2,
    hwModelSlug: "TLORA_V1",
    platformioTarget: "tlora-v1",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 3,
    hwModelSlug: "TLORA_V2_1_1P6",
    platformioTarget: "tlora-v2-1-1_6",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 4,
    hwModelSlug: "TBEAM",
    platformioTarget: "tbeam",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 5,
    hwModelSlug: "HELTEC_V2_0",
    platformioTarget: "heltec-v2_0",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 6,
    hwModelSlug: "TBEAM_V0P7",
    platformioTarget: "tbeam0_7",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 7,
    hwModelSlug: "T_ECHO",
    platformioTarget: "t-echo",
    architecture: "nrf52840",
    activelySupported: true,
  },
  {
    hwModel: 8,
    hwModelSlug: "TLORA_V1_1P3",
    platformioTarget: "tlora-v1_3",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 9,
    hwModelSlug: "RAK4631",
    platformioTarget: "rak4631",
    architecture: "nrf52840",
    activelySupported: true,
  },
  {
    hwModel: 10,
    hwModelSlug: "HELTEC_V2_1",
    platformioTarget: "heltec-v2_1",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 11,
    hwModelSlug: "HELTEC_V1",
    platformioTarget: "heltec-v1",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 12,
    hwModelSlug: "TBEAM_S3_CORE",
    platformioTarget: "tbeam-s3-core",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 13,
    hwModelSlug: "RAK11200",
    platformioTarget: "rak11200",
    architecture: "esp32",
    activelySupported: false,
  },
  {
    hwModel: 14,
    hwModelSlug: "NANO_G1",
    platformioTarget: "nano-g1",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 15,
    hwModelSlug: "TLORA_V2_1_1P8",
    platformioTarget: "tlora-v2-1-1_8",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 16,
    hwModelSlug: "TLORA_T3_S3",
    platformioTarget: "tlora-t3s3-v1",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 17,
    hwModelSlug: "NANO_G1_EXPLORER",
    platformioTarget: "nano-g1-explorer",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 18,
    hwModelSlug: "NANO_G2_ULTRA",
    platformioTarget: "nano-g2-ultra",
    architecture: "nrf52840",
    activelySupported: true,
  },
  {
    hwModel: 25,
    hwModelSlug: "STATION_G1",
    platformioTarget: "station-g1",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 26,
    hwModelSlug: "RAK11310",
    platformioTarget: "rak11310",
    architecture: "rp2040",
    activelySupported: true,
  },
  {
    hwModel: 39,
    hwModelSlug: "DIY_V1",
    platformioTarget: "meshtastic-diy-v1",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 41,
    hwModelSlug: "DR_DEV",
    platformioTarget: "meshtastic-dr-dev",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 42,
    hwModelSlug: "M5STACK",
    platformioTarget: "m5stack-core",
    architecture: "esp32",
    activelySupported: true,
  },
  {
    hwModel: 43,
    hwModelSlug: "HELTEC_V3",
    platformioTarget: "heltec-v3",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 44,
    hwModelSlug: "HELTEC_WSL_V3",
    platformioTarget: "heltec-wsl-v3",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 47,
    hwModelSlug: "RPI_PICO",
    platformioTarget: "pico",
    architecture: "rp2040",
    activelySupported: true,
  },
  {
    hwModel: 48,
    hwModelSlug: "HELTEC_WIRELESS_TRACKER",
    platformioTarget: "heltec-wireless-tracker",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 49,
    hwModelSlug: "HELTEC_WIRELESS_PAPER",
    platformioTarget: "heltec-wireless-paper",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 50,
    hwModelSlug: "T_DECK",
    platformioTarget: "t-deck",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 51,
    hwModelSlug: "T_WATCH_S3",
    platformioTarget: "t-watch-s3",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 52,
    hwModelSlug: "PICOMPUTER_S3",
    platformioTarget: "picomputer-s3",
    architecture: "esp32-s3",
    activelySupported: true,
  },
  {
    hwModel: 53,
    hwModelSlug: "HELTEC_HT62",
    platformioTarget: "heltec-ht62-esp32c3-sx1262",
    architecture: "esp32-c3",
    activelySupported: true,
  },
];

export { deviceHardwareList }