/**
 * Builds the six documents that ship compiled into the Worker bundle.
 *
 * They live in the bundle rather than in R2 on purpose: they are the payloads with real
 * consumers, so having them versioned with the code means `wrangler rollback` reverts data and
 * routing together, atomically, with no window where a new Worker reads an old object. It also
 * costs zero R2 reads on the hot path.
 *
 * The output is a PURE FUNCTION OF THE TREE. No clock, no network, no environment. CI builds
 * twice and diffs, so anything non-deterministic here fails the build. Wall-clock freshness
 * lives in `_meta.json`, which is written to R2 by the publisher instead.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolveDeviceLinks } from "../src/lib/deviceLinks.js";
import { deviceHardwareList } from "../src/lib/resource.js";
import { canonical, etagOf } from "./canonical.js";

const readJson = (path: string) => JSON.parse(readFileSync(path, "utf8"));

/**
 * `generatedAt` is the commit time of the catalog file, not the build time. The old server
 * stamped `new Date()` at first request, so the value drifted with process restarts and told you
 * when the server booted rather than when the data changed -- live it read 8+ hours stale. Taking
 * it from git makes a no-op sync produce no commit, hence no new bytes and no new timestamp,
 * which is what keeps the determinism check and the byte-parity diff meaningful.
 */
const commitTimeOf = (path: string): string => {
  const raw = execFileSync("git", ["log", "-1", "--format=%cI", "--", path], {
    encoding: "utf8",
  }).trim();
  if (!raw) {
    throw new Error(
      `no commit found for ${path} -- build-data needs full history (actions/checkout fetch-depth: 0)`,
    );
  }
  return new Date(raw).toISOString();
};

const documents = {
  DEVICE_HARDWARE: canonical(deviceHardwareList),
  DEVICE_LINKS: canonical(
    resolveDeviceLinks(commitTimeOf("data/deviceLinks.json")),
  ),
  EVENT_FIRMWARE: canonical(readJson("data/eventFirmware.json")),
  BOOTLOADER_OTA_QUIRKS: canonical(readJson("data/bootloaderOtaQuirks.json")),
  MAINTENANCE_UF2: canonical(readJson("data/maintenanceUf2.json")),
  UPDATER_MANIFEST: canonical(readJson("data/updater.manifest.json")),
} as const;

const lines = [
  "// GENERATED by tools/build-data.ts -- do not edit, do not commit.",
  "// Bodies are the exact response bytes; ETags are sha256 over those bytes.",
  "",
  "export interface Doc {",
  "  readonly body: string;",
  "  readonly etag: string;",
  "}",
  "",
];

for (const [name, body] of Object.entries(documents)) {
  lines.push(
    `export const ${name}: Doc = Object.freeze({`,
    `  body: ${JSON.stringify(body)},`,
    `  etag: ${JSON.stringify(etagOf(body))},`,
    "});",
    "",
  );
}

mkdirSync("worker/src/generated", { recursive: true });
writeFileSync("worker/src/generated/documents.ts", lines.join("\n"));

for (const [name, body] of Object.entries(documents)) {
  console.log(
    `${name.padEnd(22)} ${String(Buffer.byteLength(body)).padStart(9)} B  ${etagOf(body)}`,
  );
}
